spring:
  datasource:
    url: jdbc:h2:file:~/posts.db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
posts-service:
  url: https://jsonplaceholder.typicode.com/posts